### Import Packages

In [1]:
import numpy as np
from sklearn import datasets

### Create Dataset

In [15]:
dataset = datasets.load_diabetes()
y = dataset.target
X = dataset.data

# X = np.array([[1, 1],
#               [2, 1],
#               [2, 2],
#               [3, 4]])

# y = np.array([2, 3, 4, 6])

X = np.insert(X, 0, 1, axis = 1)

### Solve for Beta_hats

In [16]:
Xt = np.transpose(X)
Xt_X_inv = np.linalg.inv(np.dot(Xt, X))

beta_hat = np.linalg.multi_dot([Xt_X_inv, Xt, y])

beta_hat

array([ 152.13348416,  -10.01219782, -239.81908937,  519.83978679,
        324.39042769, -792.18416163,  476.74583782,  101.04457032,
        177.06417623,  751.27932109,   67.62538639])

### Compute Predictions

In [17]:
y_hat = np.dot(X, beta_hat)

y_hat

array([206.11706979,  68.07234761, 176.88406035, 166.91796559,
       128.45984241, 106.34908972,  73.89417947, 118.85378669,
       158.81033076, 213.58408893,  97.07853583,  95.1016223 ,
       115.06673301, 164.67605023, 103.07517946, 177.17236996,
       211.75953205, 182.84424343, 147.99987605, 124.01702527,
       120.33094632,  85.80377894, 113.11286302, 252.44934852,
       165.48821056, 147.72187623,  97.12824075, 179.09342974,
       129.05497324, 184.78138552, 158.71515746,  69.47588393,
       261.50255826, 112.81897436,  78.37194762,  87.66624129,
       207.92460213, 157.87686037, 240.84370686, 136.93372685,
       153.48187659,  74.15703284, 145.63105805,  77.8280105 ,
       221.0786645 , 125.22224022, 142.60147066, 109.4926324 ,
        73.14037106, 189.87368742, 157.93636782, 169.55816531,
       134.18186217, 157.72356219, 139.1077439 ,  72.73252701,
       207.8289973 ,  80.10834588, 104.08562488, 134.57807971,
       114.23779529, 180.67760064,  61.12644508,  98.72

### Compute RMSE

In [18]:
rmse = np.sqrt(np.sum((y - y_hat) ** 2) / y.shape[0])

rmse

53.47607314274362

### Hat Matrix

In [9]:
Xt = np.transpose(X)
Xt_X_inv = np.linalg.inv(np.dot(Xt, X))

H = np.linalg.multi_dot([X, Xt_X_inv, Xt])

np.dot(H, y)

array([30.00384338, 25.02556238, 30.56759672, 28.60703649, 27.94352423,
       25.25628446, 23.00180827, 19.53598843, 11.52363685, 18.92026211,
       18.99949651, 21.58679568, 20.90652153, 19.55290281, 19.28348205,
       19.29748321, 20.52750979, 16.91140135, 16.17801106, 18.40613603,
       12.52385753, 17.67103669, 15.83288129, 13.80628535, 15.67833832,
       13.38668561, 15.46397655, 14.70847428, 19.54737285, 20.8764282 ,
       11.45511759, 18.05923295,  8.81105736, 14.28275814, 13.70675891,
       23.81463526, 22.34193708, 23.10891142, 22.91502612, 31.35762569,
       34.21510225, 28.02056414, 25.20386628, 24.60979273, 22.94149176,
       22.09669817, 20.42320032, 18.03655088,  9.10655377, 17.20607751,
       21.28152535, 23.97222285, 27.6558508 , 24.04901809, 15.3618477 ,
       31.15264947, 24.85686978, 33.10919806, 21.77537987, 21.08493555,
       17.8725804 , 18.51110208, 23.98742856, 22.55408869, 23.37308644,
       30.36148358, 25.53056512, 21.11338564, 17.42153786, 20.78

### Standard Error of Betas

In [10]:
rmse = np.sqrt(np.sum((y - y_hat) ** 2) / y.shape[0])
Xt_X_inv = np.linalg.inv(np.dot(Xt, X))

var_beta = rmse * Xt_X_inv
np.diagonal(var_beta)

array([5.41218974e+00, 2.24445501e-04, 3.91583386e-05, 7.85838185e-04,
       1.54253404e-01, 3.03188157e+00, 3.62945165e-02, 3.62606083e-05,
       8.26670587e-03, 9.14700757e-04, 2.93861973e-06, 3.55661561e-03,
       1.49914785e-06, 5.34467633e-04])